#!/usr/bin/env python3
"""Insert B-roll <video> elements into index.html.

B-roll clips live at assets/intermediates/broll/broll-NN.mp4 (generated by the
OpenRouter B-roll script). This inserts one .broll-frame video per clip into
the top-frame shell, with alternating pan directions and 0.22s soft transitions.

Usage (run from the job workspace):
    python3 scripts/add-broll.py <start1> <start2> ...

Example (4 inserts at 15s/35s/55s/75s):
    python3 scripts/add-broll.py 15 35 55 75

Rules enforced (Template 01 / v88):
- Each insert is 3 seconds long.
- Inserts must be >= 6s apart and within the composition duration.
- Re-running replaces any previously inserted B-roll block.
- The clip file assets/intermediates/broll/broll-NN.mp4 must exist for each
  start position given (NN = 01, 02, ... in order).
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "index.html"
BROLL_DURATION = 3
MIN_SPACING = 6

PAN_PRESETS = [
    ("50% 51%", "50% 49%"),
    ("51% 50%", "49% 50%"),
    ("49% 50%", "51% 50%"),
    ("50% 49%", "50% 51%"),
]


def broll_tag(index: int, start: float) -> str:
    pan_from, pan_to = PAN_PRESETS[index % len(PAN_PRESETS)]
    nn = f"{index + 1:02d}"
    return (
        f'        <video id="broll{nn}" class="clip top-media broll-frame" '
        f'data-layout-allow-overflow="true" '
        f'src="assets/intermediates/broll/broll-{nn}.mp4" '
        f'data-start="{start:.3f}" data-duration="{BROLL_DURATION}" data-media-start="0" '
        f'data-transition-mode="soft" data-transition-in="0.22" data-transition-out="0.22" '
        f'data-pan-from="{pan_from}" data-pan-to="{pan_to}" '
        f'data-motion-kind="slow-broll-inner-zoom" data-motion-duration="{BROLL_DURATION}" '
        f'data-track-index="{4 + index}" data-volume="0" muted playsinline></video>'
    )


def main():
    starts = sys.argv[1:]
    if not starts:
        print("Usage: python3 scripts/add-broll.py <start1> <start2> ...", file=sys.stderr)
        print("Example: python3 scripts/add-broll.py 15 35 55 75", file=sys.stderr)
        sys.exit(1)

    try:
        positions = sorted(float(s) for s in starts)
    except ValueError:
        print("Error: all start positions must be numbers", file=sys.stderr)
        sys.exit(1)

    # Validate spacing
    for a, b in zip(positions, positions[1:]):
        if b - a < MIN_SPACING:
            print(f"Error: B-roll starts {a} and {b} are < {MIN_SPACING}s apart", file=sys.stderr)
            sys.exit(1)

    html = INDEX.read_text(encoding="utf-8")

    # Validate against composition duration
    m = re.search(r'id="root"[^>]*data-duration="(\d+\.?\d*)"', html)
    comp_dur = float(m.group(1)) if m else None
    if comp_dur:
        for p in positions:
            if p + BROLL_DURATION > comp_dur:
                print(f"Error: B-roll at {p}s + {BROLL_DURATION}s exceeds composition {comp_dur}s",
                      file=sys.stderr)
                sys.exit(1)

    # Remove any existing broll elements
    html = re.sub(r'\s*<video\s+id="broll\d+"[\s\S]*?</video>\s*\n', '\n', html)

    # Build the new block
    tags = "\n\n".join(broll_tag(i, p) for i, p in enumerate(positions))
    block = f"\n\n{tags}\n\n"

    # Insert right after the topVideo element
    m_top = re.search(r'(<video id="topVideo"[\s\S]*?</video>)', html)
    if not m_top:
        print("Error: could not find #topVideo in index.html", file=sys.stderr)
        sys.exit(1)
    insert_at = m_top.end()
    html = html[:insert_at] + block + html[insert_at:]

    INDEX.write_text(html, encoding="utf-8")
    clips = ", ".join(f"broll-{i + 1:02d} @ {p}s" for i, p in enumerate(positions))
    print(f"  Inserted {len(positions)} B-roll element(s): {clips}")
    print(f"  Each {BROLL_DURATION}s, soft 0.22s transitions, tracks 4-{3 + len(positions)}")


if __name__ == "__main__":
    main()
